### ISSUE TITLE
Cache Money and background-fu

### ISSUE THREAD

**Issue by ponny** [ncr/background-fu#1]
When I try to add a job, it goes crazy on me - 

> > Job.enqueue!(ExampleWorker, :add, 1, 2).id
> >  RuntimeError: repository delegated to @cache_config.repository, but @cache_config is nil: Job(id: integer, worker_class: string, worker_method: string, args: text, result: text, priority: integer, progress: integer, state: string, lock_version: integer, start_at: datetime, started_at: datetime, created_at: datetime, updated_at: datetime)

Any ideas?

**Comment by ncr** [comment]
repository delegated to @cache_config.repository, but @cache_config is nil - I don't think this is coming from b-fu, can't really help here without more info.
